<?php
// $Id$

/**
 * @file
 *   Provides install and uninstall functions for commentrss.
 */

/**
 * Implementation of hook_uninstall().
 */
function commentrss_uninstall() {
  // Delete all variables.
  variable_del('commentrss_site');
  variable_del('commentrss_node');
  variable_del('commentrss_term');
}

/**
 * Empty update since menu items have changed.
 */
function commentrss_update_6200() {
  return array();
}
