<?php
// $Id$

function commentrss_help($section="admin/modules#description") {
  if ($section == "admin/modules#description") {
    return t('Provides RSS feeds for comments');
  }
}

function commentrss_menu($may_cache) {
  $items = array();
  if ($may_cache) {
    $items[] = array('path' => 'crss', 'title' => '',
      'callback' => 'commentrss_handler',
      'access' => user_access('access content'),
      'type' => MENU_CALLBACK);
  }
  return $items;
}

function commentrss_handler() {
  $type = arg(1);
  if ($type) {
    if (in_array($type, array('node', 'term', 'vocab', 'nodetype'))) {
      if (call_user_func('commentrss_feed_' . $type)) {
        return;
      }
    }
  }
  else {
    if (commentrss_feed_site()) {
      return;
    }
  }
  drupal_not_found();
}

// Provides a comment feed for the complete Drupal site (ie. all nodes)
function commentrss_feed_site() {
  $items = commentrss_format_items();
  commentrss_format_feed($items);
  return TRUE;
}

// Provides a comment feed for nodes in a vocabulary
// For the master link in the RSS feed to work, you need vocabulary_list.module!
function commentrss_feed_vocab() {
  global $base_url;
  
  $vid = arg(2);
  if (is_numeric($vid)) {
    
    // Get nids for this term
    $nids = array();
    $result = db_query("SELECT DISTINCT(n.nid) FROM {node} n INNER JOIN {term_node} r ON n.nid = r.nid INNER JOIN {term_data} d ON r.tid = d.tid WHERE d.vid = %d AND n.status = '1'", $vid);
    while ($node = db_fetch_object($result)) {
      $nids[] = $node->nid;
    }
    
    // No relevant nids found for this vocabulary
    if (!count($nids)) { return FALSE; }
    
    $items = commentrss_format_items('nid IN (' . join(', ', $nids) . ')');
    $vocab = taxonomy_get_vocabulary($vid);
    
    // We can link to a specific page if vocabulary listing is present
    $link = (module_exist('vocabulary_list') ? url("taxonomy/vocabulary/$vid", NULL, NULL, TRUE) : $base_url);
    
    $channel = array(
      'title'       => variable_get('site_name', 'drupal') .' - '. $vocab->name .' - '. t('Comments'),
      'link'        => $link,
      'description' => t('Comments for "%title"', array("%title" => $vocab->name)),
    );
    
    commentrss_format_feed($items, $channel);
    return TRUE;
  }
  return FALSE;
}

// Provides a comment feed for nodes associated with a term
function commentrss_feed_term() {
  $tid = arg(2);
  if (is_numeric($tid)) {
    
    // Get nids for this term
    $nids = array();
    $result = db_query("SELECT DISTINCT(n.nid) FROM {node} n INNER JOIN {term_node} r ON n.nid = r.nid WHERE r.tid = %d AND n.status = '1'", $tid);
    while ($node = db_fetch_object($result)) {
      $nids[] = $node->nid;
    }
    
    // No relevant nids found for this term
    if (!count($nids)) { return FALSE; }
    
    $items = commentrss_format_items('nid IN (' . join(', ', $nids) . ')');
    $term = taxonomy_get_term($tid);
    
    $channel = array(
      'title'       => variable_get('site_name', 'drupal') .' - '. $term->name .' - '. t('Comments'),
      'link'        => url("taxonomy/term/$tid", NULL, NULL, TRUE),
      'description' => t('Comments for "%title"', array("%title" => $term->name)),
    );
    
    commentrss_format_feed($items, $channel);
    return TRUE;
  }
  return FALSE;
}

// Provides a comment feed for a single node (also includes the node teaser
// as the last item, even if there are too many comments which are not
// included in the resulting RSS output)
function commentrss_feed_node() {
  
  $nid = arg(2);
  if (is_numeric($nid)) {
    $node = node_load(array('nid' => $nid));
    
    // No node found for this ID
    if (!$node) { return FALSE; }

    $items = commentrss_format_items("nid = $nid");
    $link = url("node/$nid", NULL, NULL, TRUE);
    $items .= format_rss_item($node->title, $link, ($node->teaser ? $node->teaser : $node->body), array('pubDate' => date('r', $node->changed)));
    
    $channel = array(
      'title'       => variable_get('site_name', 'drupal') .' - '. $node->title .' - '. t('Comments'),
      'link'        => $link,
      'description' => t('Comments for "%title"', array("%title" => $node->title)),
    );
    
    commentrss_format_feed($items, $channel);
    return TRUE;
  }
  return FALSE;
}

// Provides a comment feed for nodes of a certain type
function commentrss_feed_nodetype() {
  $type = arg(2);
  if (preg_match("!^[a-z0-9-]+$!", $type)) {
    
    // Get nids for this node type
    $nids = array();
    $result = db_query("SELECT nid FROM {node} WHERE type = '%s' AND status = '1'", $type);
    while ($node = db_fetch_object($result)) {
      $nids[] = $node->nid;
    }
    
    // No relevant nids found for this node type
    if (!count($nids)) { return FALSE; }
    
    $items = commentrss_format_items('nid IN (' . join(', ', $nids) . ')');
    $typename = node_invoke($type, 'node_name');
    
    $channel = array(
      'title'       => variable_get('site_name', 'drupal') .' - '. $typename .' - '. t('Comments'),
      //'link'        => url("nodesbytype/$type", NULL, NULL, TRUE),
      'description' => t('Comments for "%type"', array("%type" => $typename)),
    );
    
    commentrss_format_feed($items, $channel);
    return TRUE;
  }
  return FALSE;
}

// Format a comment feed with the given items and print the output
// This is a customized version of the core node_feed()
function commentrss_format_feed($items, $channel = array()) {
  global $base_url;
  
  $languages = (function_exists('locale') ? locale_supported_languages() : array('name' => array('en' => 'English')));
  $channel_defaults = array(
    'version'     => '0.92',
    'title'       => variable_get('site_name', 'drupal') . ' - ' . t('Comments'),
    'link'        => $base_url,
    'description' => t('Comments'),
    'language'    => (($key = reset(array_keys($languages['name']))) ? $key : 'en')
  );
  $channel = array_merge($channel_defaults, $channel);
  
  $output = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n";
  $output .= "<!DOCTYPE rss [<!ENTITY % HTMLlat1 PUBLIC \"-//W3C//ENTITIES Latin 1 for XHTML//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml-lat1.ent\">]>\n";
  $output .= "<rss version=\"". $channel["version"] . "\" xml:base=\"". $base_url ."\">\n";
  $output .= format_rss_channel($channel['title'], $channel['link'], $channel['description'], $items, $channel['language']);
  $output .= "</rss>\n";

  drupal_set_header('Content-Type: text/xml; charset=utf-8');
  print $output;
}

// Format RSS for comments sent in reply to the nodes selected by the given SQL selector
function commentrss_format_items($nodeselector = NULL) {
  
  $items = '';
  $nodeselector = ((isset($nodeselector) && strlen($nodeselector)) ? "AND $nodeselector" : '');
  
  $comments = db_query_range("SELECT cid, nid, subject, comment, timestamp FROM {comments} WHERE status = 0 $nodeselector ORDER BY timestamp DESC", 0, 15);
    
  while ($comment = db_fetch_object($comments)) {
    $link = url("node/view/{$comment->nid}", NULL, "comment-{$comment->cid}", TRUE);
    $items .= format_rss_item($comment->subject, $link, $comment->comment, array('pubDate' => date('r', $comment->timestamp)));
  }
  return $items;
}
